version: '3'
services:
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - SANITY_PROJECT_ID=${SANITY_PROJECT_ID}
  #     - SANITY_DATASET=${SANITY_DATASET}
  #     - SANITY_SECRET_TOKEN=${SANITY_SECRET_TOKEN}
  #     - JWT_SECRETS=${JWT_SECRETS}
  #     - JWT_NAME=${JWT_NAME}
  #     - API_PORT=${API_PORT}

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
